apiVersion: v1
kind: PersistentVolumeClaim
metadata:
#  => mysql volume claimName
  name: webook-mysql-live-claim
spec:
  storageClassName: chrisstorage
  accessModes:
    - ReadWriteOnce
#    - ReadOnlyMany
#    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

  