// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"go_work/user_webook/internal/repository"
	"go_work/user_webook/internal/repository/cache"
	"go_work/user_webook/internal/repository/dao"
	"go_work/user_webook/internal/service"
	"go_work/user_webook/internal/web"
	"go_work/user_webook/ioc"
)

// Injectors from wire.go:


func InitWebServer() *gin.Engine {
	v := ioc.InitMiddlewares()
	db := ioc.InitDb()
	userDAOInter := dao.NewGORMUserDAO(db)
	cmdable := ioc.InitRedis()
	userCacheInter := cache.NewUserCache(cmdable)
	userRepositoryRepInter := repository.NewUserRepository(userDAOInter, userCacheInter)
	userServiceInter := service.NewUserService(userRepositoryRepInter)
	codeCacheInter := cache.NewCodeCache(cmdable)
	codeRepositoryInter := repository.NewCodeRepository(codeCacheInter)
	codeServiceInter := service.NewCodeService(codeRepositoryInter)
	userHandler := web.NewUserHandler(userServiceInter, codeServiceInter)
	engine := ioc.InitWebServer(v, userHandler)
	return engine
}
